# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # 사용자가 깃헙페이지에서 수동으로 동작시키기위한 설정
  workflow_dispatch:

# 스크립트 내에서 사용할 환경변수 추가
env:
  S3_BUCKET_NAME: ae-stagram-deploy
  S3_BUCKET_REGION: ap-northeast-2
  PROJECT_NAME: demo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 해당 저장소의 코드를 가져온다.
      - name: Checkout
        uses: actions/checkout@v2

      - name: 자바 1.8 설치
        uses: actions/setup-java@v1
        with: 
          java-version: 1.8

      - name: Gradlew 권한 설정
        run: chmod +x gradlew
        shell: bash
          
      - name: 빌드
        run: ./gradlew build 
        shell: bash

      - name: 프로젝트 Zip 파일로 압축
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $S3_BUCKET_REGION

      - name: Upload to S3
        run: aws s3 cp --region $S3_BUCKET_REGION ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

